### ISSUE TITLE
Missing letter errors in the transliterator

### ISSUE THREAD

**Issue by aharonium** [opensiddur/opensiddur#152]
I tried transliterating with the first blessing of arvit and I saw transliteration errors across all transliteration schema options. Just for an example, here's the Academy for the Hebrew Language transliteration schema. Just in the first line I'm seeing a missing bet, tav, and shuruks. In the second line I'm seeing a missing ḥolam...

בָּרוּךְ אַתָּה יְהֹוָ֑ה אֱלֹהֵֽינוּ
מֶֽלֶךְ הָעוֹלָם
אֲשֶׁר בִּדְבָרוֹ 
מַעֲרִיב עֲרָבִים 
בְּחָכְמָה פּוֹתֵֽחַ שְׁעָרִים 
בִּתְבוּנָה מְשַׁנֶּה עִתִּים 
וּמַחֲלִיף אֶת־הַזְּמַנִּים 
וּמְסַדֵּר אֶת־הַכּוֹכָבִים
בְּמִשְׁמְרוֹתֵֽיהֶם בָּרָקִֽיעַ 
כְּרְצוֹנוֹ: 
בּוֹרֵא יוֹם וָלָֽיְלָה 
גּוֹלֵל אוֹר מִפְּנֵי חֹֽשֶׁךְ 
וְחֹֽשֶׁךְ מִפְּנֵי אוֹר: 
וּמַעֲבִיר יוֹם וּמֵֽבִיא לָֽיְלָה 
וּמַבְדִּיל בֵּין יוֹם וּבֵין לָֽיְלָה 
יְהֹוָ֑ה צְבָאוֹת שְׁמוֹ: (אֵל חַי וְקַיָּם תָּמִיד יִמְלוךְ עָלֵינוּ לְעולָם וָעֶד:)
בָּרוּךְ אַתָּה יְהֹוָ֑ה הַמַּעֲרִיב עֲרָבִים:

converts to 

arkh ˈaa ˈadoonay ˈelohen
melekh haˈlam
ˈaer idvar 
maˈariv ˈaravim 
eẖakhema teaẖ eˈarim 
bitvna meaeh ˈiim 
maẖalif ˈet-hamaim 
msaer ˈet-hakhavim
emimertehem arakiaˈ 
retsn 
reˈ ym valayela 
lel ˈr mine ẖoekh 
veẖoekh mine ˈr 
maˈavir ym meviˈ layela 
mavil en ym ven layela 
ˈadoonay tsevaˈt em ˈel ẖay vekayyam tamid yimlvkh ˈalenu leˈvlam vaˈed
arkh ˈaa ˈadoonay haaˈariv ˈaravim

**Comment by aharonium** [comment]
I think I found the cause of the error. 

Adobe InDesign and perhaps other applications will modify pointed Hebrew text by replacing Hebrew letters with dagesh marks (including shuruk, and maybe some other cases), with the unicode version of the letters combined with the dagesh. Visually, no difference can be seen, however, the transliterator demo doesn't know what to do with the ligature so it is ignored.

**Comment by marcstober** [comment]
This is an issue of Unicode Normal Forms as described at https://en.wikipedia.org/wiki/Unicode_equivalence. A better solution might be to use an available algorithm to turn everything into Normal Form D (separate characters, which seems more common for Hebrew although not all languages) before running it through the transliterator. The advantage would be not only that you wouldn't have longer transliteration tables but that you wouldn't have a bug caused by, for example, a bet plus a dagesh (as separate characters) transliterating to something different than the single-character equivalent.

**Comment by aharonium** [comment]
Question: 

I just tested the transliterator using the text above and saw the same error result. 

e.g. בָּרוּךְ ↔ "arkh" 
because the bet and the shuruk aren't recognized...

Is this issue resolved?  Maybe I'm not seeing the fix because the server needs to be rebuilt or something...

**Comment by EfraimFeinstein** [comment]
The fix is in develop. It isn't yet deployed.
